#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

log() {
  printf '\n==> %s\n' "$*"
}

require_file() {
  [[ -f "$1" ]] || die "Run this script from the demo-openchoreo-deployment repository root; missing: $1"
}

require_file "demo.sh"
require_file "scripts/bootstrap-all.sh"
require_file "scripts/rancher.sh"
require_file "scripts/self-test.sh"
require_file "services/platform-portal/index.html"

STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP_DIR="runtime/showcase-upgrade-backup-${STAMP}"
mkdir -p "$BACKUP_DIR"

backup() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  mkdir -p "$BACKUP_DIR/$(dirname "$f")"
  cp -p "$f" "$BACKUP_DIR/$f"
}

for f in \
  demo.sh \
  scripts/rancher.sh \
  services/platform-portal/index.html \
  README.md
do
  backup "$f"
done

mkdir -p scripts docs runtime

log "Creating immutable Rancher image freeze helper"
cat > scripts/showcase-freeze-rancher.sh <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

SOURCE_IMAGE="${1:-${RANCHER_SOURCE_IMAGE:-rancher/rancher:latest}}"
ENV_FILE="${SHOWCASE_ENV_FILE:-runtime/showcase.env}"

command -v docker >/dev/null 2>&1 || {
  echo "ERROR: docker is required." >&2
  exit 1
}

mkdir -p "$(dirname "$ENV_FILE")"

echo "Pulling Rancher image used for event qualification: $SOURCE_IMAGE"
docker pull "$SOURCE_IMAGE"

DIGEST="$(
  docker image inspect "$SOURCE_IMAGE" \
    --format '{{index .RepoDigests 0}}' 2>/dev/null || true
)"

if [[ -z "$DIGEST" || "$DIGEST" != *@sha256:* ]]; then
  echo "ERROR: Could not resolve an immutable RepoDigest for $SOURCE_IMAGE." >&2
  exit 1
fi

cat > "$ENV_FILE" <<ENV
# Generated by scripts/showcase-freeze-rancher.sh.
# Source tag used for qualification: $SOURCE_IMAGE
export RANCHER_IMAGE='$DIGEST'
export ENABLE_RANCHER='1'
export RANCHER_REQUIRED='1'
export SHOWCASE_STRICT='1'
export SHOWCASE_REQUIRE_RANCHER='1'
ENV
chmod 600 "$ENV_FILE"

echo
echo "Rancher is frozen to:"
echo "  $DIGEST"
echo
echo "Next:"
echo "  source $ENV_FILE"
echo "  ./demo.sh reset"
echo "  ./demo.sh readiness"
EOF

log "Creating live OpenChoreo capability evidence script"
cat > scripts/showcase-capabilities.sh <<'EOF'
#!/usr/bin/env bash
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

REPORT="${SHOWCASE_CAPABILITY_REPORT:-runtime/showcase-capabilities.md}"
mkdir -p "$(dirname "$REPORT")"
: > "$REPORT"

FAILURES=0
WARNINGS=0

emit() {
  printf '%s\n' "$*" | tee -a "$REPORT"
}

pass() {
  emit "- PASS — $*"
}

warn() {
  WARNINGS=$((WARNINGS + 1))
  emit "- WARN — $*"
}

fail() {
  FAILURES=$((FAILURES + 1))
  emit "- FAIL — $*"
}

have() {
  command -v "$1" >/dev/null 2>&1
}

count_resource() {
  local resource="$1"
  local namespace="${2:-}"
  local out

  if [[ -n "$namespace" ]]; then
    out="$(kubectl get "$resource" -n "$namespace" -o name 2>/dev/null || true)"
  else
    out="$(kubectl get "$resource" -A -o name 2>/dev/null || true)"
  fi

  if [[ -z "$out" ]]; then
    printf '0'
  else
    printf '%s\n' "$out" | awk 'NF {n++} END {print n+0}'
  fi
}

object_exists() {
  local resource="$1"
  local name="$2"
  local namespace="${3:-}"

  if [[ -n "$namespace" ]]; then
    kubectl get "$resource" "$name" -n "$namespace" >/dev/null 2>&1
  else
    kubectl get "$resource" "$name" >/dev/null 2>&1
  fi
}

check_count() {
  local label="$1"
  local resource="$2"
  local expected="$3"
  local namespace="${4:-}"
  local actual
  actual="$(count_resource "$resource" "$namespace")"

  if [[ "$actual" == "$expected" ]]; then
    pass "$label: $actual"
  else
    fail "$label: expected $expected, found $actual"
  fi
}

check_object() {
  local label="$1"
  local resource="$2"
  local name="$3"
  local namespace="${4:-}"

  if object_exists "$resource" "$name" "$namespace"; then
    pass "$label: $name"
  else
    fail "$label missing: $name"
  fi
}

emit "# OpenChoreo live capability evidence"
emit
emit "Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
emit
emit "This report proves the platform state used by the showcase. It intentionally separates OpenChoreo platform capabilities from Kubernetes/Rancher runtime visibility."
emit

if ! have kubectl; then
  fail "kubectl is not installed"
  emit
  emit "Result: FAILED"
  exit 1
fi

if ! kubectl cluster-info >/dev/null 2>&1; then
  fail "Kubernetes cluster is not reachable"
  emit
  emit "Result: FAILED"
  exit 1
fi

NS="${OPENCHOREO_DEMO_NAMESPACE:-platform-demo}"

emit "## Platform topology"
check_count "Projects" "projects.openchoreo.dev" 10 "$NS"
check_count "Components" "components.openchoreo.dev" 19 "$NS"
check_count "ProjectReleaseBindings" "projectreleasebindings.openchoreo.dev" 30 "$NS"
check_object "Development environment" "environments.openchoreo.dev" "development" "$NS"
check_object "Staging environment" "environments.openchoreo.dev" "staging" "$NS"
check_object "Production environment" "environments.openchoreo.dev" "production" "$NS"
check_object "Deployment pipeline" "deploymentpipelines.openchoreo.dev" "platform-standard" "$NS"

emit
emit "## Platform engineering and governance"
check_object "Regulated golden path / ProjectType" "clusterprojecttypes.openchoreo.dev" "regulated-platform"
check_object "Managed cache ResourceType" "clusterresourcetypes.openchoreo.dev" "platform-valkey-cache"
check_object "Managed payment cache resource" "resources.openchoreo.dev" "payment-idempotency-cache" "$NS"
check_object "Policy workflow" "workflows.openchoreo.dev" "platform-policy-gate" "$NS"
check_object "Platform auditor role" "authzroles.openchoreo.dev" "platform-auditor" "$NS"
check_object "Developer scoped authorization binding" "clusterauthzrolebindings.openchoreo.dev" "platform-demo-developers"
check_object "Auditor authorization binding" "authzrolebindings.openchoreo.dev" "platform-demo-auditors" "$NS"

emit
emit "## OpenChoreo planes"
for r in \
  clusterdataplanes.openchoreo.dev \
  clusterworkflowplanes.openchoreo.dev \
  clusterobservabilityplanes.openchoreo.dev
do
  n="$(count_resource "$r")"
  if [[ "$n" -ge 1 ]]; then
    pass "$r: $n configured"
  else
    fail "$r: none configured"
  fi
done

emit
emit "## Observability and operations"
CHANNELS="$(count_resource "observabilityalertsnotificationchannels.openchoreo.dev" "$NS")"
if [[ "$CHANNELS" -ge 3 ]]; then
  pass "Alert notification channels: $CHANNELS"
else
  warn "Expected environment-specific alert channels; found $CHANNELS"
fi

PAYMENTS_JSON="$(kubectl get components.openchoreo.dev payments-service -n "$NS" -o json 2>/dev/null || true)"
for evidence in "triggerAiRca" "budget" "cpu"; do
  if grep -qi "$evidence" <<<"$PAYMENTS_JSON"; then
    pass "Payments observability evidence contains '$evidence'"
  else
    warn "Payments observability evidence '$evidence' was not found in the live Component"
  fi
done

emit
emit "## Agentic platform operations"
CONTROL_NS="${OPENCHOREO_CONTROL_PLANE_NAMESPACE:-openchoreo-control-plane}"
OBS_NS="${OPENCHOREO_OBSERVABILITY_PLANE_NAMESPACE:-openchoreo-observability-plane}"

for pair in \
  "$CONTROL_NS:portal-assistant:Portal Assistant" \
  "$OBS_NS:sre-agent:SRE Agent" \
  "$OBS_NS:finops-agent:FinOps Agent"
do
  IFS=: read -r ns dep label <<<"$pair"
  if kubectl get deployment "$dep" -n "$ns" >/dev/null 2>&1; then
    ready="$(kubectl get deployment "$dep" -n "$ns" -o jsonpath='{.status.readyReplicas}' 2>/dev/null || true)"
    desired="$(kubectl get deployment "$dep" -n "$ns" -o jsonpath='{.spec.replicas}' 2>/dev/null || true)"
    ready="${ready:-0}"
    desired="${desired:-0}"
    if [[ "$desired" -gt 0 && "$ready" -ge "$desired" ]]; then
      pass "$label: ready ($ready/$desired)"
    else
      warn "$label exists but is not fully ready ($ready/$desired)"
    fi
  else
    warn "$label is not enabled in this runtime"
  fi
done

emit
emit "## Kubernetes and SUSE Rancher evidence"
OPS_DEP="$(kubectl get deployment -A -o name 2>/dev/null | grep -E 'k8s-ops|kubernetes-ops' | head -1 || true)"
if [[ -n "$OPS_DEP" ]]; then
  pass "Kubernetes Operations Console deployment is present"
else
  warn "Kubernetes Operations Console deployment was not located automatically"
fi

if command -v docker >/dev/null 2>&1 && docker inspect platform-rancher >/dev/null 2>&1; then
  RANCHER_RUNNING="$(docker inspect -f '{{.State.Running}}' platform-rancher 2>/dev/null || true)"
  RANCHER_IMAGE_LIVE="$(docker inspect -f '{{.Config.Image}}' platform-rancher 2>/dev/null || true)"
  if [[ "$RANCHER_RUNNING" == "true" ]]; then
    pass "SUSE Rancher container is running ($RANCHER_IMAGE_LIVE)"
  else
    fail "SUSE Rancher container exists but is not running"
  fi

  if "$ROOT/scripts/rancher.sh" verify >/dev/null 2>&1; then
    pass "Rancher can reach the imported OpenChoreo Kubernetes cluster"
  else
    warn "Rancher is running but imported-cluster verification did not pass"
  fi
else
  warn "SUSE Rancher container is not running"
fi

emit
emit "## Result"
if [[ "$FAILURES" -eq 0 ]]; then
  emit "READY — ${WARNINGS} warning(s)."
  emit
  emit "OpenChoreo remains the developer-platform/control-plane story; Rancher provides complementary Kubernetes fleet/runtime visibility."
  exit 0
else
  emit "NOT READY — ${FAILURES} failure(s), ${WARNINGS} warning(s)."
  exit 1
fi
EOF

log "Creating strict event readiness gate"
cat > scripts/showcase-readiness.sh <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if [[ -f runtime/showcase.env ]]; then
  # shellcheck disable=SC1091
  source runtime/showcase.env
fi

echo "==> 1/5 Source and manifest self-test"
./scripts/self-test.sh

echo
echo "==> 2/5 Clean-room/runtime verification"
./demo.sh verify

echo
echo "==> 3/5 Event-determinism checks"
if [[ "${SHOWCASE_STRICT:-0}" == "1" ]]; then
  if [[ -z "${RANCHER_IMAGE:-}" ]]; then
    echo "ERROR: SHOWCASE_STRICT=1 but RANCHER_IMAGE is unset." >&2
    exit 1
  fi
  if [[ "$RANCHER_IMAGE" == *":latest" ]]; then
    echo "ERROR: SHOWCASE_STRICT=1 refuses a mutable Rancher :latest tag." >&2
    echo "Run: ./scripts/showcase-freeze-rancher.sh" >&2
    exit 1
  fi
  if [[ "$RANCHER_IMAGE" != *@sha256:* ]]; then
    echo "ERROR: SHOWCASE_STRICT=1 requires Rancher to be pinned by digest." >&2
    exit 1
  fi
  echo "PASS: Rancher image is immutable: $RANCHER_IMAGE"
else
  echo "WARN: SHOWCASE_STRICT is not enabled; suitable for development, not event qualification."
fi

echo
echo "==> 4/5 SUSE Rancher verification"
if [[ "${SHOWCASE_REQUIRE_RANCHER:-${RANCHER_REQUIRED:-0}}" == "1" ]]; then
  ./scripts/rancher.sh verify
else
  ./scripts/rancher.sh verify || echo "WARN: Rancher verification is optional in this run."
fi

echo
echo "==> 5/5 OpenChoreo capability proof"
./scripts/showcase-capabilities.sh

if [[ "${SHOWCASE_REQUIRE_AI:-0}" == "1" ]]; then
  echo
  echo "==> Required AI-agent readiness"
  kubectl rollout status deployment/portal-assistant -n "${OPENCHOREO_CONTROL_PLANE_NAMESPACE:-openchoreo-control-plane}" --timeout=120s
  kubectl rollout status deployment/sre-agent -n "${OPENCHOREO_OBSERVABILITY_PLANE_NAMESPACE:-openchoreo-observability-plane}" --timeout=120s
  kubectl rollout status deployment/finops-agent -n "${OPENCHOREO_OBSERVABILITY_PLANE_NAMESPACE:-openchoreo-observability-plane}" --timeout=120s
fi

echo
echo "SHOWCASE READINESS: PASS"
echo "Evidence: runtime/showcase-capabilities.md"
EOF

log "Creating event preparation helper"
cat > scripts/showcase-prepare.sh <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if [[ ! -f runtime/showcase.env ]]; then
  echo "ERROR: runtime/showcase.env does not exist." >&2
  echo "Freeze a qualified Rancher image first:" >&2
  echo "  ./scripts/showcase-freeze-rancher.sh" >&2
  exit 1
fi

# shellcheck disable=SC1091
source runtime/showcase.env

if [[ "${SHOWCASE_ENABLE_AI:-0}" == "1" ]]; then
  if [[ -z "${OPENAI_API_KEY:-}" ]]; then
    echo "ERROR: SHOWCASE_ENABLE_AI=1 requires OPENAI_API_KEY." >&2
    exit 1
  fi

  export OPENCHOREO_AGENT_MODEL="${OPENCHOREO_AGENT_MODEL:-gpt-5.4}"
  ./scripts/enable-ai-agents.sh
  export SHOWCASE_REQUIRE_AI=1
fi

./scripts/showcase-readiness.sh

echo
echo "Operator launch points"
echo "----------------------"
./demo.sh status || true
echo
echo "Recommended presentation order:"
echo "  1. Financial business outcome in the custom experience"
echo "  2. OpenChoreo Backstage portal: System/Component views"
echo "  3. ProjectType, cells, releases, resources, authorization, observability"
echo "  4. Policy workflow / promotion"
echo "  5. Kubernetes Operations Console as runtime proof"
echo "  6. SUSE Rancher for the same Kubernetes estate"
echo "  7. SRE / FinOps / Portal Assistant when enabled"
EOF

log "Creating architecture/capability map"
cat > docs/SHOWCASE-CAPABILITY-MAP.md <<'EOF'
# OpenChoreo Financial Services Showcase — Capability Map

This environment is designed to demonstrate **OpenChoreo as the developer platform** and **SUSE Rancher as complementary Kubernetes management/visibility**. Rancher is not presented as the OpenChoreo control plane.

## Story architecture

| Customer question | OpenChoreo capability shown | Live evidence |
|---|---|---|
| How do platform teams provide safe self-service? | ProjectTypes / platform abstractions / golden paths | `regulated-platform` creates per-environment Cell infrastructure, quotas, limits, security labels and baseline network policy |
| How is regulated software organized? | Namespaces, Projects, Components, Workloads, Cells | 10 Projects / 19 Components across financial services and telecom domains |
| How do changes move safely? | Immutable releases, ReleaseBindings, ProjectReleaseBindings, DeploymentPipeline | development → staging → production promotion |
| How are environment differences controlled? | Environment configuration and release binding overrides | environment-specific quotas, cache size and observability settings |
| How are dependencies handled? | Component endpoint dependencies and generated networking | payment/customer/risk/compliance dependency graph |
| How do teams consume platform services? | Resources and ResourceTypes | managed Valkey idempotency cache |
| How is cross-cutting behavior standardized? | Traits | observability/alert/RCA/FinOps configuration on services |
| How is access governed? | Declarative OpenChoreo authorization | scoped developer/auditor bindings; production restrictions |
| How are operational gates encoded? | Workflow Plane / Argo workflows | security-scan and change-ticket policy workflow |
| How do teams observe systems? | Logs, metrics, traces, alerts, incidents, RCA and cost views | OpenChoreo observability and Backstage entity views |
| How does AI assist operations? | SRE Agent, FinOps Agent, Portal Assistant | optional pre-enabled agents, using current supported model configuration |
| Can operators still see Kubernetes? | Open underlying Kubernetes data plane | Kubernetes Operations Console |
| Where does SUSE Rancher fit? | Complementary Kubernetes fleet/runtime management | imported OpenChoreo k3d cluster, namespaces, workloads and cluster agents visible in Rancher |

## Presentation rule

Use the **OpenChoreo Backstage portal as the primary platform evidence**. The custom portal is the scenario launcher and business-value view. Kubernetes Operations and Rancher are runtime evidence and operational views of the same underlying Kubernetes estate.

## Official documentation anchors

- OpenChoreo docs: https://openchoreo.dev/docs/
- Architecture: https://openchoreo.dev/docs/overview/architecture/
- Backstage-powered developer portal: https://openchoreo.dev/explore/backstage-powered-developer-portal/
- ProjectTypes: https://openchoreo.dev/docs/platform-engineer-guide/project-types/
- Authorization: https://openchoreo.dev/docs/platform-engineer-guide/authorization/
- GitOps: https://openchoreo.dev/docs/category/gitops/
- GitOps with Flux CD: https://openchoreo.dev/docs/platform-engineer-guide/gitops/using-flux-cd/
- SRE Agent: https://openchoreo.dev/docs/ai/sre-agent/
- Portal Assistant: https://openchoreo.dev/docs/ai/portal-assistant/

## Production-relevance caveat

The demo's local managed cache is intentionally a local showcase ResourceType. Do not characterize its embedded demo credentials/provisioning pattern as a production banking secret-management solution. The platform abstraction is the capability being demonstrated; a production installation should bind the ResourceType to the organization's approved managed service/provisioner and secret-management implementation.
EOF

log "Creating concise operator runbook"
cat > docs/SHOWCASE-RUNBOOK.md <<'EOF'
# OpenChoreo Financial Services Showcase — Operator Runbook

## Qualification, before the event

From the repository root:

```bash
./scripts/showcase-freeze-rancher.sh
source runtime/showcase.env
./demo.sh reset
./demo.sh readiness
```

If AI capabilities are part of the presentation, enable them during qualification rather than during the customer conversation:

```bash
source runtime/showcase.env
export OPENAI_API_KEY='...'
export OPENCHOREO_AGENT_MODEL='gpt-5.4'
export SHOWCASE_ENABLE_AI=1
./demo.sh prepare
unset OPENAI_API_KEY
```

Run `./demo.sh readiness` again after every machine restart, network change, Docker/Colima restart, or source modification.

## Customer story

Start with a banking outcome in the Financial Experience. Follow the transaction into OpenChoreo and show the System/Component views, rather than immediately opening Kubernetes.

Then show how the platform team encoded the regulated golden path: `regulated-platform`, the three-environment pipeline, immutable releases and bindings, the managed cache Resource, Traits, authorization boundaries, and the workflow policy gate.

Use observability as a connected story: logs/metrics/traces → alert → RCA/cost analysis. If the built-in agents are enabled, demonstrate them from OpenChoreo; keep the Portal Assistant framed as read-only assistance.

Only then move down one level to Kubernetes Operations to prove that OpenChoreo is deploying real Kubernetes workloads and enforcing generated runtime controls.

Finish in SUSE Rancher. Show the same cluster, namespaces, workloads and Rancher agents. The message is complementarity: OpenChoreo provides the developer-platform abstraction, software delivery and governance; Rancher gives the infrastructure/operator view of the Kubernetes estate.

## Recovery

The presentation path must always remain available without AI-provider access. AI is an enhancement, not a prerequisite for the core OpenChoreo demonstration.

For a clean reset:

```bash
source runtime/showcase.env
./demo.sh reset
./demo.sh readiness
```

For controlled scenario resets, keep using the repository's existing `./demo.sh scenario ...` flows.
EOF

log "Patching Rancher helper with strict-event guard"
python3 - <<'PY'
from pathlib import Path

p = Path("scripts/rancher.sh")
s = p.read_text()

marker = "# SHOWCASE_STRICT_RANCHER_PIN"
if marker not in s:
    needle = 'RANCHER_IMAGE="${RANCHER_IMAGE:-rancher/rancher:latest}"'
    if needle not in s:
        raise SystemExit("Could not locate RANCHER_IMAGE assignment in scripts/rancher.sh")

    replacement = needle + r'''

# SHOWCASE_STRICT_RANCHER_PIN
# Development keeps the repository's convenient :latest default. A qualified
# event run can opt into an immutable digest by sourcing runtime/showcase.env.
if [[ "${SHOWCASE_STRICT:-0}" == "1" ]]; then
  if [[ "$RANCHER_IMAGE" == *":latest" ]]; then
    die "SHOWCASE_STRICT=1 refuses mutable Rancher tag: $RANCHER_IMAGE. Run ./scripts/showcase-freeze-rancher.sh first."
  fi
  if [[ "$RANCHER_IMAGE" != *@sha256:* ]]; then
    die "SHOWCASE_STRICT=1 requires Rancher to be pinned by immutable digest; got: $RANCHER_IMAGE"
  fi
fi'''
    s = s.replace(needle, replacement, 1)
    p.write_text(s)
PY

log "Adding root-level demo commands"
python3 - <<'PY'
from pathlib import Path

p = Path("demo.sh")
s = p.read_text()

if 'showcase-capabilities.sh' not in s:
    needle = '  scenario)\n'
    if needle not in s:
        raise SystemExit("Could not locate scenario command in demo.sh")

    commands = r'''  capabilities)
    "$ROOT/scripts/showcase-capabilities.sh"
    ;;
  readiness)
    "$ROOT/scripts/showcase-readiness.sh"
    ;;
  prepare)
    "$ROOT/scripts/showcase-prepare.sh"
    ;;
  ai)
    "$ROOT/scripts/enable-ai-agents.sh"
    ;;
'''
    s = s.replace(needle, commands + needle, 1)

s = s.replace(
    'Usage: ./demo.sh [up|reset|verify|status|rancher|scenario|stop|start|destroy]',
    'Usage: ./demo.sh [up|reset|verify|status|capabilities|readiness|prepare|ai|rancher|scenario|stop|start|destroy]'
)

p.write_text(s)
PY

log "Making the custom portal platform-first"
python3 - <<'PY'
from pathlib import Path
import re

p = Path("services/platform-portal/index.html")
s = p.read_text()

replacements = {
    "<title>Platform Application</title>":
        "<title>OpenChoreo Financial Services Platform</title>",
    '<div class="logo">P</div><div>Platform<br>Application</div>':
        '<div class="logo">OC</div><div>OpenChoreo<br>Financial Platform</div>',
    "Platform Runtime":
        "Platform Capabilities",
    "OpenChoreo reference application":
        "Financial services platform engineering · OpenChoreo + SUSE Rancher",
    "One cluster · multiple domains":
        "Governed developer platform · visible Kubernetes",
    "Show application delivery, governance and runtime operations from one polished experience.":
        "Build, deploy, govern and operate regulated workloads through OpenChoreo — with the same Kubernetes estate visible in SUSE Rancher.",
    "Use the financial and telecom stories to establish business value, then inspect the same platform through Kubernetes Operations or Rancher.":
        "Start with a financial outcome, then trace it through OpenChoreo projects, Cells, releases, resources, observability and policy controls. Use Kubernetes Operations and Rancher as runtime evidence, not as substitutes for the developer platform.",
    '<div><strong>Business domains</strong><span>2</span></div>':
        '<div><strong>Projects</strong><span>10</span></div>',
    '<div><strong>Environment</strong><span>DEV</span></div>':
        '<div><strong>Components</strong><span>19</span></div>',
    '<div><strong>Platform layer</strong><span>K8s</span></div>':
        '<div><strong>Environments</strong><span>3</span></div>',
    "'Platform runtime'":
        "'Platform capabilities'",
}
for old, new in replacements.items():
    s = s.replace(old, new)

new_platform = r'''<section id="platform" class="page">
  <div class="section-head">
    <div>
      <div class="eyebrow">OpenChoreo platform evidence</div>
      <h2>From golden path to governed runtime</h2>
      <p>The business applications are deliberately built on platform primitives that can be inspected live. OpenChoreo owns the developer-platform abstraction and delivery model; Kubernetes and SUSE Rancher remain visible underneath.</p>
    </div>
  </div>

  <div class="cards">
    <article class="card">
      <div class="eyebrow">Developer self-service</div>
      <h3>Backstage developer experience</h3>
      <p>Projects, Systems, Components and live entity views connect software ownership to builds, deployments, logs, events, metrics, alerts, traces, incidents, RCA and cost analysis.</p>
      <div class="status ok">OPENCHOREO</div>
    </article>
    <article class="card">
      <div class="eyebrow">Golden paths</div>
      <h3>ProjectType + platform abstractions</h3>
      <p>The regulated platform template generates per-environment Cell infrastructure, quotas, limits, security labels, baseline isolation and operational RBAC from reusable platform policy.</p>
      <div class="status ok">SELF-SERVICE</div>
    </article>
    <article class="card">
      <div class="eyebrow">Software delivery</div>
      <h3>Immutable releases + promotion</h3>
      <p>ReleaseBindings and ProjectReleaseBindings separate immutable software from environment-specific configuration and drive the development → staging → production lifecycle.</p>
      <div class="status ok">GOVERNED</div>
    </article>
    <article class="card">
      <div class="eyebrow">Platform services</div>
      <h3>Resources + ResourceTypes</h3>
      <p>The payment domain consumes a managed Valkey idempotency cache as a platform resource, demonstrating how application teams request capabilities instead of hand-building infrastructure.</p>
      <div class="status ok">MANAGED</div>
    </article>
    <article class="card">
      <div class="eyebrow">Cross-cutting standards</div>
      <h3>Traits + observability</h3>
      <p>Reusable operational behavior carries alerting, AI-assisted RCA signals and FinOps evidence into workloads without pushing those concerns into business-service code.</p>
      <div class="status ok">OBSERVABLE</div>
    </article>
    <article class="card">
      <div class="eyebrow">Regulated-platform controls</div>
      <h3>Authorization + policy workflows</h3>
      <p>Declarative scoped authorization protects production operations while the workflow plane models security-scan and change-ticket gates for controlled promotion.</p>
      <div class="status ok">CONTROLLED</div>
    </article>
    <article class="card">
      <div class="eyebrow">Agentic operations</div>
      <h3>SRE, FinOps + Portal Assistant</h3>
      <p>Optional OpenChoreo agents turn telemetry and platform context into root-cause, cost and developer assistance while keeping the Portal Assistant read-only by contract.</p>
      <div class="status">OPTIONAL</div>
    </article>
    <article class="card">
      <div class="eyebrow">Runtime evidence</div>
      <h3>Kubernetes Operations</h3>
      <p>Inspect the real Kubernetes workloads and execute intentionally constrained demo operations to prove that the platform abstractions resolve to standard Kubernetes resources.</p>
      <div class="status ok">KUBERNETES</div>
    </article>
    <article class="card">
      <div class="eyebrow">SUSE partnership story</div>
      <h3>Rancher sees the same estate</h3>
      <p>Open the imported cluster in SUSE Rancher to inspect namespaces, workloads and cluster agents from the infrastructure/operator perspective. Rancher complements OpenChoreo; it does not replace its control plane.</p>
      <div class="status ok">RANCHER</div>
    </article>
  </div>
</section>'''

pattern = re.compile(r'<section id="platform" class="page">.*?</section>', re.S)
if pattern.search(s):
    s = pattern.sub(new_platform, s, count=1)
else:
    raise SystemExit("Could not locate platform section in services/platform-portal/index.html")

p.write_text(s)
PY

log "Adding showcase guidance to README"
python3 - <<'PY'
from pathlib import Path

p = Path("README.md")
s = p.read_text()

marker = "<!-- OPENCHOREO_SHOWCASE_UPGRADE -->"
if marker not in s:
    addition = r'''

<!-- OPENCHOREO_SHOWCASE_UPGRADE -->
## Qualified customer showcase mode

The normal developer flow remains `./demo.sh up` / `./demo.sh reset`. For customer-facing event qualification, use the stricter workflow below so that the Rancher image is immutable and the full OpenChoreo capability set is checked before presentation:

```bash
./scripts/showcase-freeze-rancher.sh
source runtime/showcase.env
./demo.sh reset
./demo.sh readiness
```

Useful commands:

```bash
./demo.sh capabilities   # live platform capability evidence
./demo.sh readiness      # source + runtime + Rancher + capability gate
./demo.sh prepare        # final operator preparation
./demo.sh ai             # enable OpenChoreo AI agents (requires provider key)
```

See `docs/SHOWCASE-CAPABILITY-MAP.md` and `docs/SHOWCASE-RUNBOOK.md` for the platform story and presentation sequence.
'''
    p.write_text(s.rstrip() + addition + "\n")
PY

chmod +x \
  scripts/showcase-freeze-rancher.sh \
  scripts/showcase-capabilities.sh \
  scripts/showcase-readiness.sh \
  scripts/showcase-prepare.sh

log "Validating shell syntax"
for f in \
  demo.sh \
  scripts/rancher.sh \
  scripts/showcase-freeze-rancher.sh \
  scripts/showcase-capabilities.sh \
  scripts/showcase-readiness.sh \
  scripts/showcase-prepare.sh
do
  bash -n "$f"
done

log "Running repository source self-test"
./scripts/self-test.sh

log "Upgrade applied successfully"
printf '\nBackup of modified files: %s\n' "$BACKUP_DIR"
cat <<'EOF'

Recommended next steps:

  ./scripts/showcase-freeze-rancher.sh
  source runtime/showcase.env
  ./demo.sh reset
  ./demo.sh readiness

For the optional OpenChoreo SRE / FinOps / Portal Assistant capabilities,
enable them during event qualification rather than during the live conversation:

  source runtime/showcase.env
  export OPENAI_API_KEY='...'
  export OPENCHOREO_AGENT_MODEL='gpt-5.4'
  export SHOWCASE_ENABLE_AI=1
  ./demo.sh prepare
  unset OPENAI_API_KEY
EOF
