const fs=require('fs');const path=require('path');const https=require('https');const {start,json,text,body}=require('../lib/http');const index=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const tokenPath='/var/run/secrets/kubernetes.io/serviceaccount/token',caPath='/var/run/secrets/kubernetes.io/serviceaccount/ca.crt';
function kreq(method,p,payload,contentType='application/json'){return new Promise((resolve,reject)=>{const token=fs.readFileSync(tokenPath,'utf8').trim(),ca=fs.readFileSync(caPath);const data=payload?JSON.stringify(payload):null;const r=https.request({hostname:'kubernetes.default.svc',port:443,path:p,method,ca,headers:{authorization:`Bearer ${token}`,accept:'application/json',...(data?{'content-type':contentType,'content-length':Buffer.byteLength(data)}:{})}},res=>{let raw='';res.on('data',c=>raw+=c);res.on('end',()=>{let d={};try{d=raw?JSON.parse(raw):{}}catch{d={raw}};if(res.statusCode<200||res.statusCode>=300)return reject(new Error(`Kubernetes API ${res.statusCode}: ${raw.slice(0,240)}`));resolve(d)})});r.on('error',reject);r.setTimeout(8000,()=>r.destroy(new Error('Kubernetes API timeout')));if(data)r.write(data);r.end()})}
const get=p=>kreq('GET',p);function compactPod(x){const cs=x.status?.containerStatuses||[];return {namespace:x.metadata.namespace,name:x.metadata.name,phase:x.status?.phase,node:x.spec?.nodeName,ready:cs.length?cs.filter(c=>c.ready).length+'/'+cs.length:'—',restarts:cs.reduce((a,c)=>a+(c.restartCount||0),0),age:x.metadata.creationTimestamp,component:x.metadata.labels?.['openchoreo.dev/component']||''}}
function inDemo(ns){return typeof ns==='string'&&ns.startsWith('dp-platform-demo-')}
start({name:'k8s-ops-console',routes:async(req,res,u)=>{if(req.method==='GET'&&u.pathname==='/')return text(res,200,index,'text/html; charset=utf-8');
 if(req.method==='GET'&&u.pathname==='/api/summary'){const [pods,deps,svcs,routes,nps,comps,rbs]=await Promise.all([get('/api/v1/pods'),get('/apis/apps/v1/deployments'),get('/api/v1/services'),get('/apis/gateway.networking.k8s.io/v1/httproutes'),get('/apis/networking.k8s.io/v1/networkpolicies'),get('/apis/openchoreo.dev/v1alpha1/namespaces/platform-demo/components'),get('/apis/openchoreo.dev/v1alpha1/namespaces/platform-demo/releasebindings')]);const dp=pods.items.filter(x=>inDemo(x.metadata.namespace));return json(res,200,{pods:dp.length,running:dp.filter(x=>x.status.phase==='Running').length,deployments:deps.items.filter(x=>inDemo(x.metadata.namespace)).length,services:svcs.items.filter(x=>inDemo(x.metadata.namespace)).length,routes:routes.items.filter(x=>inDemo(x.metadata.namespace)).length,networkPolicies:nps.items.filter(x=>inDemo(x.metadata.namespace)).length,components:comps.items.length,releaseBindings:rbs.items.length})}
 if(req.method==='GET'&&u.pathname==='/api/pods'){const d=await get('/api/v1/pods');return json(res,200,{items:d.items.filter(x=>inDemo(x.metadata.namespace)).map(compactPod)})}
 if(req.method==='GET'&&u.pathname==='/api/deployments'){const d=await get('/apis/apps/v1/deployments');return json(res,200,{items:d.items.filter(x=>inDemo(x.metadata.namespace)).map(x=>({namespace:x.metadata.namespace,name:x.metadata.name,ready:`${x.status.readyReplicas||0}/${x.spec.replicas||1}`,available:x.status.availableReplicas||0,component:x.metadata.labels?.['openchoreo.dev/component']||'',age:x.metadata.creationTimestamp}))})}
 if(req.method==='GET'&&u.pathname==='/api/services'){const d=await get('/api/v1/services');return json(res,200,{items:d.items.filter(x=>inDemo(x.metadata.namespace)).map(x=>({namespace:x.metadata.namespace,name:x.metadata.name,type:x.spec.type,clusterIP:x.spec.clusterIP,ports:x.spec.ports?.map(p=>`${p.port}/${p.protocol}`).join(', ')}))})}
 if(req.method==='GET'&&u.pathname==='/api/routes'){const d=await get('/apis/gateway.networking.k8s.io/v1/httproutes');return json(res,200,{items:d.items.filter(x=>inDemo(x.metadata.namespace)).map(x=>({namespace:x.metadata.namespace,name:x.metadata.name,hostnames:x.spec.hostnames||[],parents:(x.status?.parents||[]).map(p=>p.conditions?.find(c=>c.type==='Accepted')?.status||'Unknown')}))})}
 if(req.method==='GET'&&u.pathname==='/api/networkpolicies'){const d=await get('/apis/networking.k8s.io/v1/networkpolicies');return json(res,200,{items:d.items.filter(x=>inDemo(x.metadata.namespace)).map(x=>({namespace:x.metadata.namespace,name:x.metadata.name,podSelector:x.spec.podSelector,policyTypes:x.spec.policyTypes||[]}))})}
 if(req.method==='GET'&&u.pathname==='/api/events'){const d=await get('/api/v1/events?limit=150');return json(res,200,{items:d.items.filter(x=>inDemo(x.metadata.namespace)).sort((a,b)=>String(b.lastTimestamp||b.eventTime||'').localeCompare(String(a.lastTimestamp||a.eventTime||''))).slice(0,80).map(x=>({namespace:x.metadata.namespace,type:x.type,reason:x.reason,message:x.message,object:`${x.involvedObject.kind}/${x.involvedObject.name}`,time:x.lastTimestamp||x.eventTime||x.metadata.creationTimestamp}))})}
 if(req.method==='GET'&&u.pathname==='/api/openchoreo'){const [c,r,p]=await Promise.all([get('/apis/openchoreo.dev/v1alpha1/namespaces/platform-demo/components'),get('/apis/openchoreo.dev/v1alpha1/namespaces/platform-demo/releasebindings'),get('/apis/openchoreo.dev/v1alpha1/namespaces/platform-demo/projectreleasebindings')]);return json(res,200,{components:c.items.map(x=>({name:x.metadata.name,project:x.spec.owner?.projectName,type:x.spec.componentType?.name})),releaseBindings:r.items.map(x=>({name:x.metadata.name,project:x.spec.owner?.projectName||x.spec.project,ready:(x.status?.conditions||[]).find(c=>c.type==='Ready')?.status||'Unknown'})),projectReleaseBindings:p.items.map(x=>({name:x.metadata.name,release:x.spec.projectRelease,ready:(x.status?.conditions||[]).find(c=>c.type==='Ready')?.status||'Unknown'}))})}
 if(req.method==='POST'&&u.pathname==='/api/actions/restart'){const p=await body(req);if(!inDemo(p.namespace))return json(res,403,{error:'Demo namespaces only'});await kreq('PATCH',`/apis/apps/v1/namespaces/${encodeURIComponent(p.namespace)}/deployments/${encodeURIComponent(p.name)}`,{spec:{template:{metadata:{annotations:{'platform.demo/restartedAt':new Date().toISOString()}}}}},'application/strategic-merge-patch+json');return json(res,200,{ok:true,action:'restart',namespace:p.namespace,name:p.name})}
 if(req.method==='POST'&&u.pathname==='/api/actions/delete-pod'){const p=await body(req);if(!inDemo(p.namespace))return json(res,403,{error:'Demo namespaces only'});await kreq('DELETE',`/api/v1/namespaces/${encodeURIComponent(p.namespace)}/pods/${encodeURIComponent(p.name)}`);return json(res,200,{ok:true,action:'delete-pod',namespace:p.namespace,name:p.name})}
 return false;}});
