const fs=require('fs');const path=require('path');const {start,json,text,body,log}=require('../lib/http');const {request,MCPClient,resultText}=require('../lib/mcp');
const index=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
let tokenCache={token:null,exp:0};
async function openChoreoToken(){if(process.env.OPENCHOREO_MCP_TOKEN)return process.env.OPENCHOREO_MCP_TOKEN;if(tokenCache.token&&Date.now()<tokenCache.exp-60000)return tokenCache.token;const client=process.env.OPENCHOREO_MCP_CLIENT_ID||'service_mcp_client';const secret=process.env.OPENCHOREO_MCP_CLIENT_SECRET||'service_mcp_client_secret';const auth=Buffer.from(`${client}:${secret}`).toString('base64');const r=await request(process.env.OPENCHOREO_TOKEN_URL||'http://host.k3d.internal:8080/oauth2/token',{headers:{'content-type':'application/x-www-form-urlencoded','authorization':`Basic ${auth}`,'host':process.env.OPENCHOREO_TOKEN_HOST||'thunder.openchoreo.localhost'},body:'grant_type=client_credentials'});if(r.status!==200)throw new Error(`OpenChoreo OAuth token ${r.status}: ${r.text.slice(0,300)}`);const d=JSON.parse(r.text);tokenCache={token:d.access_token,exp:Date.now()+(d.expires_in||3600)*1000};return d.access_token;}
function mcpUrl(value){if(!value)return value;try{const u=new URL(value);if(!u.pathname||u.pathname==='/' )u.pathname='/mcp';return u.toString();}catch{return value.endsWith('/mcp')?value:`${value.replace(/\/$/,'')}/mcp`;}}
async function clients(){let token=null;try{token=await openChoreoToken()}catch(e){log('openchoreo_token_failed',{error:e.message})}const defs=[
 {label:'openchoreo_control',url:process.env.CONTROL_MCP_URL||'http://host.k3d.internal:8080/mcp',headers:{...(token?{authorization:`Bearer ${token}`} : {}),host:process.env.CONTROL_MCP_HOST||'api.openchoreo.localhost'}},
 {label:'openchoreo_observability',url:process.env.OBS_MCP_URL||'http://host.k3d.internal:11080/mcp',headers:{...(token?{authorization:`Bearer ${token}`} : {}),host:process.env.OBS_MCP_HOST||'observer.openchoreo.localhost'}},
 {label:'customer',url:mcpUrl(process.env.CUSTOMER_MCP_URL),headers:{}},{label:'risk',url:mcpUrl(process.env.RISK_MCP_URL),headers:{}},{label:'compliance',url:mcpUrl(process.env.COMPLIANCE_MCP_URL),headers:{}}
].filter(x=>x.url);return defs.map(d=>({label:d.label,client:new MCPClient({name:d.label,url:d.url,headers:d.headers})}));}
function safeName(s){return s.replace(/[^a-zA-Z0-9_]/g,'_').slice(0,64)}
async function discover(){const cs=await clients();const catalog=[];const status=[];for(const c of cs){try{const tools=await c.client.tools();status.push({server:c.label,ok:true,toolCount:tools.length});for(const t of tools)catalog.push({server:c.label,client:c.client,mcpName:t.name,name:safeName(`${c.label}__${t.name}`),description:`[${c.label}] ${t.description||t.name}`,inputSchema:t.inputSchema||{type:'object',properties:{}}});}catch(e){status.push({server:c.label,ok:false,error:e.message,toolCount:0});}}return {catalog,status};}
async function openai(apiKey,prompt,catalog,trace){let input=prompt;let previous=null;const tools=catalog.map(t=>({type:'function',name:t.name,description:t.description,parameters:t.inputSchema,strict:false}));for(let turn=0;turn<7;turn++){const payload={model:process.env.OPENAI_MODEL||'gpt-5.4',input,tools,tool_choice:'auto'};if(previous)payload.previous_response_id=previous;const r=await request('https://api.openai.com/v1/responses',{headers:{'content-type':'application/json','authorization':`Bearer ${apiKey}`},body:JSON.stringify(payload)});if(r.status<200||r.status>=300)throw new Error(`OpenAI ${r.status}: ${r.text.slice(0,500)}`);const resp=JSON.parse(r.text);previous=resp.id;const calls=(resp.output||[]).filter(x=>x.type==='function_call');if(!calls.length){const texts=[];for(const o of resp.output||[])for(const c of o.content||[])if(c.type==='output_text')texts.push(c.text);return texts.join('\n')||resp.output_text||'Completed.';}const outputs=[];for(const call of calls){const t=catalog.find(x=>x.name===call.name);if(!t){outputs.push({type:'function_call_output',call_id:call.call_id,output:'Tool not found'});continue;}let args={};try{args=JSON.parse(call.arguments||'{}')}catch{}const started=Date.now();try{const result=await t.client.call(t.mcpName,args);const out=resultText(result);trace.push({server:t.server,tool:t.mcpName,args,ok:true,durationMs:Date.now()-started,preview:out.slice(0,800)});outputs.push({type:'function_call_output',call_id:call.call_id,output:out});}catch(e){trace.push({server:t.server,tool:t.mcpName,args,ok:false,durationMs:Date.now()-started,error:e.message});outputs.push({type:'function_call_output',call_id:call.call_id,output:`ERROR: ${e.message}`});}}
 input=outputs;}
return 'Agent reached its tool-call turn limit.';}
function schemaArgs(tool,candidates={}){const props=(tool.inputSchema&&tool.inputSchema.properties)||{};const out={};for(const key of Object.keys(props)){if(Object.prototype.hasOwnProperty.call(candidates,key)){out[key]=candidates[key];continue;}const k=key.toLowerCase().replace(/[_-]/g,'');if(k.includes('namespace'))out[key]='platform-demo';else if(k.includes('project'))out[key]='payments';else if(k.includes('component'))out[key]='payments-service';else if(k.includes('environment'))out[key]='development';else if(k.includes('customer'))out[key]='C001';}return out;}
async function scripted(prompt,catalog,trace){const call=async(server,name,candidates={})=>{const t=catalog.find(x=>x.server===server&&x.mcpName===name);if(!t)return null;const args=schemaArgs(t,candidates);try{const r=await t.client.call(name,args);const out=resultText(r);trace.push({server,tool:name,args,ok:true,preview:out.slice(0,800)});return out}catch(e){trace.push({server,tool:name,args,ok:false,error:e.message});return null}};
const results=[];results.push(await call('openchoreo_control','list_namespaces',{}));results.push(await call('openchoreo_control','list_projects',{namespace:'platform-demo',namespaceName:'platform-demo'}));results.push(await call('customer','get_customer_profile',{customerId:'C001'}));results.push(await call('customer','list_customer_accounts',{customerId:'C001'}));results.push(await call('risk','get_fraud_signals',{}));results.push(await call('compliance','list_payment_policies',{}));if(/incident|error|sre|failure/i.test(prompt)){const filter={namespace:'platform-demo',namespaceName:'platform-demo',project:'payments',projectName:'payments',component:'payments-service',componentName:'payments-service',environment:'development',environmentName:'development'};results.push(await call('openchoreo_observability','query_alerts',filter));results.push(await call('openchoreo_observability','query_incidents',filter));}return `Scripted platform-safe mode executed real MCP calls across the connected platform.\n\n${results.filter(Boolean).slice(-5).join('\n\n')}`;}
start({name:'financial-agent',routes:async(req,res,u)=>{
 if(req.method==='GET'&&u.pathname==='/')return text(res,200,index,'text/html; charset=utf-8');
 if(req.method==='GET'&&u.pathname==='/api/mcp-status'){const d=await discover();return json(res,200,{status:d.status,tools:d.catalog.map(t=>({server:t.server,name:t.mcpName,description:t.description}))});}
 if(req.method==='POST'&&u.pathname==='/api/chat'){const p=await body(req);const trace=[];const d=await discover();const key=p.openaiApiKey||process.env.OPENAI_API_KEY;const answer=key?await openai(key,p.prompt||'',d.catalog,trace):await scripted(p.prompt||'',d.catalog,trace);return json(res,200,{mode:key?'llm':'scripted-platform-safe',model:key?(process.env.OPENAI_MODEL||'gpt-5.4'):null,answer,trace,mcpStatus:d.status});}
 return false;
}});
