#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

SOURCE_IMAGE="${1:-${RANCHER_SOURCE_IMAGE:-rancher/rancher:latest}}"
ENV_FILE="${SHOWCASE_ENV_FILE:-.showcase.env}"

command -v docker >/dev/null 2>&1 || {
  echo "ERROR: docker is required." >&2
  exit 1
}

mkdir -p "$(dirname "$ENV_FILE")"

echo "Pulling Rancher image used for event qualification: $SOURCE_IMAGE"
docker pull "$SOURCE_IMAGE"

DIGEST="$(
  docker image inspect "$SOURCE_IMAGE" \
    --format '{{index .RepoDigests 0}}' 2>/dev/null || true
)"

if [[ -z "$DIGEST" || "$DIGEST" != *@sha256:* ]]; then
  echo "ERROR: Could not resolve an immutable RepoDigest for $SOURCE_IMAGE." >&2
  exit 1
fi

cat > "$ENV_FILE" <<ENV
# Generated by scripts/showcase-freeze-rancher.sh.
# Source tag used for qualification: $SOURCE_IMAGE
export RANCHER_IMAGE='$DIGEST'
export ENABLE_RANCHER='0'
export SHOWCASE_STRICT='1'
ENV
chmod 600 "$ENV_FILE"

echo
echo "Rancher is frozen to:"
echo "  $DIGEST"
echo
echo "Next:"
echo "  source $ENV_FILE"
echo "  ./demo.sh reset"
echo "  ./demo.sh readiness"
